export const DEFAULT_PAGE_SIZE = 20;

export const POKEMON_TYPES = [
  'Fire',
  'Water',
  'Grass',
  'Lightning',
  'Psychic',
  'Fighting',
  'Colorless',
  'Darkness',
  'Metal',
  'Dragon',
  'Fairy',
];

export const STATUS = {
  IDLE: 'idle',
  LOADING: 'loading',
  SUCCESS: 'success',
  ERROR: 'error',
  EMPTY: 'empty',
};

export const TYPE_ACCENT_COLORS = {
  Fire: '#e3350d',
  Water: '#2a75bb',
  Grass: '#3fa34d',
  Lightning: '#f0b100',
  Psychic: '#c0388a',
  Fighting: '#b5442e',
  Colorless: '#8a8d99',
  Darkness: '#3a3f4b',
  Metal: '#6b7280',
  Dragon: '#6247aa',
  Fairy: '#e6739f',
};

export const DEFAULT_ACCENT_COLOR = '#e3350d';

export const TYPE_ALIASES = {
  fuego: 'Fire',
  fire: 'Fire',
  agua: 'Water',
  water: 'Water',
  planta: 'Grass',
  grass: 'Grass',
  electrico: 'Lightning',
  eléctrico: 'Lightning',
  rayo: 'Lightning',
  lightning: 'Lightning',
  psiquico: 'Psychic',
  psíquico: 'Psychic',
  psychic: 'Psychic',
  lucha: 'Fighting',
  fighting: 'Fighting',
  normal: 'Colorless',
  incoloro: 'Colorless',
  colorless: 'Colorless',
  siniestro: 'Darkness',
  oscuro: 'Darkness',
  darkness: 'Darkness',
  metal: 'Metal',
  acero: 'Metal',
  dragon: 'Dragon',
  dragón: 'Dragon',
  hada: 'Fairy',
  fairy: 'Fairy',
};

export const POKEMON_CREATURE_TYPES = [
  'normal',
  'fighting',
  'flying',
  'poison',
  'ground',
  'rock',
  'bug',
  'ghost',
  'steel',
  'fire',
  'water',
  'grass',
  'electric',
  'psychic',
  'ice',
  'dragon',
  'dark',
  'fairy',
];

export const POKEMON_CREATURE_TYPE_COLORS = {
  normal: '#a4a878',
  fighting: '#b5442e',
  flying: '#8ba7de',
  poison: '#a040a0',
  ground: '#c8a165',
  rock: '#a8a15a',
  bug: '#8fa815',
  ghost: '#705898',
  steel: '#6b7280',
  fire: '#e3350d',
  water: '#2a75bb',
  grass: '#3fa34d',
  electric: '#f0b100',
  psychic: '#c0388a',
  ice: '#5bc0d5',
  dragon: '#6247aa',
  dark: '#3a3f4b',
  fairy: '#e6739f',
};

export const POKEMON_CREATURE_TYPE_ALIASES = {
  normal: 'normal',
  lucha: 'fighting',
  fighting: 'fighting',
  volador: 'flying',
  flying: 'flying',
  veneno: 'poison',
  poison: 'poison',
  tierra: 'ground',
  ground: 'ground',
  roca: 'rock',
  rock: 'rock',
  bicho: 'bug',
  bug: 'bug',
  fantasma: 'ghost',
  ghost: 'ghost',
  acero: 'steel',
  steel: 'steel',
  fuego: 'fire',
  fire: 'fire',
  agua: 'water',
  water: 'water',
  planta: 'grass',
  grass: 'grass',
  electrico: 'electric',
  eléctrico: 'electric',
  electric: 'electric',
  psiquico: 'psychic',
  psíquico: 'psychic',
  psychic: 'psychic',
  hielo: 'ice',
  ice: 'ice',
  dragon: 'dragon',
  dragón: 'dragon',
  siniestro: 'dark',
  oscuro: 'dark',
  dark: 'dark',
  hada: 'fairy',
  fairy: 'fairy',
};

